[bar]
order = [ "default", "r-spacer" ]

    [bar.default]
    center = [ "group:g2" ]
    end = [ "privacy", "wallpaper", "volume", "group:g4", "group:g3", "tray", "notifications", "session" ]
    margin_ends = 100
    position = "left"
    start = [ "workspaces" ]

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "clock", "date" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "cpu", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = false
        fill = "surface_variant"
        id = "g4"
        members = [ "network", "bluetooth" ]
        opacity = 1.0
        padding = 6.0

    [bar.r-spacer]
    auto_hide = false
    center = [ "taskbar" ]
    enabled = true
    end = []
    position = "right"
    show_on_workspace_switch = false
    start = []

[battery]
warning_threshold = 20

[calendar]
enabled = true
refresh_minutes = 5

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[dock]
background_opacity = 1.0
cross_axis_padding = 0
enabled = false
icon_size = 24
position = "right"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Butzbach, Germany"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 125.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        center_text = true
        clock_style = "digital"
        format = "{:%H:%M:%S}"
        shadow = true

[nightlight]
enabled = true

[osd]
orientation = "vertical"
position_vertical = "center_right"

[shell]
launch_apps_as_systemd_services = true
panel_anchor_bar = "default"
polkit_agent = true
screen_time_enabled = true

    [shell.panel]
    polkit_placement = "attached"

[theme]
custom_palette = "nix"
mode = "dark"
source = "custom"

[widget.battery]
display_mode = "graphic"

[widget.network]
show_label = false

[widget.privacy.actions]
left = "mic-mute"

[widget.session]
enabled = false

[widget.taskbar]
only_active_workspace = true
scale = 1.5

[widget.tray]
drawer = true

[widget.volume]
enabled = false

[widget.wallpaper]
enabled = false
