[bar]
order = [ "default", "r-spacer" ]

    [bar.default]
    center = [ "group:g2" ]
    end = [ "privacy", "wallpaper", "volume", "group:g4", "group:g3", "tray", "notifications", "session" ]
    margin_ends = 100
    position = "left"
    start = [ "workspaces" ]

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "clock", "date" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "cpu", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = false
        fill = "surface_variant"
        id = "g4"
        members = [ "network", "bluetooth" ]
        opacity = 1.0
        padding = 6.0

    [bar.r-spacer]
    auto_hide = false
    center = [ "taskbar" ]
    enabled = false
    end = []
    position = "right"
    show_on_workspace_switch = false
    start = []

[battery]
warning_threshold = 20

[calendar]
enabled = true
refresh_minutes = 5

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[dock]
background_opacity = 1.0
cross_axis_padding = 0
enabled = true
icon_size = 24
position = "right"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Butzbach, Germany"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true

[nightlight]
enabled = true

[osd]
orientation = "vertical"
position_vertical = "center_right"

[shell]
launch_apps_as_systemd_services = true
panel_anchor_bar = "default"
polkit_agent = true
screen_time_enabled = true

    [shell.panel]
    polkit_placement = "attached"

[theme]
custom_palette = "nix"
mode = "dark"
source = "custom"

[widget.battery]
display_mode = "graphic"

[widget.network]
show_label = false

[widget.privacy.actions]
left = "mic-mute"

[widget.session]
enabled = false

[widget.taskbar]
only_active_workspace = true

[widget.tray]
drawer = true

[widget.volume]
enabled = false

[widget.wallpaper]
enabled = false
