{
  perSystem = {
    pkgs,
    theme,
    ...
  }: let
    nixIcon = pkgs.writeTextDir "share/vicinae/themes/icons/nix.svg" (
      builtins.readFile "${pkgs.nixos-icons}/share/icons/hicolor/scalable/apps/nix-snowflake.svg"
    );
    # TODO: add icon back in
    nixTheme = pkgs.writeTextDir "share/vicinae/themes/nixTheme.toml" ''
      [meta]
      version = 1
      name = "nixTheme"
      description = "this theme is generated by nix"
      variant = "dark"
      icon = "icons/nix.svg"

      [colors.core]
      background = "#${theme.colors.base00}"
      foreground = "#${theme.colors.base05}"
      secondary_background = "#${theme.colors.base11}"
      border = "#${theme.colors.base02}"
      accent = "#${theme.colors.base0D}"

      [colors.accents]
      blue = "#${theme.colors.base0D}"
      green = "#${theme.colors.base0B}"
      magenta = "#${theme.colors.base17}"
      orange = "#${theme.colors.base09}"
      purple = "#${theme.colors.base0E}"
      red = "#${theme.colors.base08}"
      yellow = "#${theme.colors.base0A}"
      cyan = "#${theme.colors.base0C}"

      [colors.list.item.selection]
      background = "#${theme.colors.base03}"
      secondary_background = "#${theme.colors.base04}"


      [colors.grid.item]
      background = "#${theme.colors.base01}"
    '';
  in {
    packages.vicinae = pkgs.symlinkJoin {
      name = "vicinae";
      paths = [
        pkgs.vicinae
        nixTheme
        nixIcon
      ];
      postBuild = ''
        rm $out/bin/vicinae
        cat <<EOF > $out/bin/vicinae
        #!/usr/bin/env bash
        export XDG_DATA_DIRS="$out/share''${XDG_DATA_DIRS:+:\$XDG_DATA_DIRS}"
        if [ "\$1" = "server" ]; then
          shift
          exec ${pkgs.vicinae}/bin/vicinae server --config ${./settings.json} "\$@"
        else
          exec ${pkgs.vicinae}/bin/vicinae "\$@"
        fi
        EOF
        chmod +x $out/bin/vicinae
      '';
    };
  };
}
