hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "default", style = "slide bottom" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "default", style = "slide bottom" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "layers", enabled = true, speed = 4, bezier = "default", style = "slide" })
hl.animation({ leaf = "fade", enabled = false })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fadePopups", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fadeDpms", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "border", enabled = false })
hl.animation({ leaf = "borderangle", enabled = false })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slide" })
